### ISSUE TITLE
Danfo renaming

### ISSUE THREAD

**Issue by tphinney** [Afrotype/danfo#10]
Remember that there is already another font in development for Google using the Danfo name, so it has to be something else. It cannot have a hyphen, nor an intercap (except in the PostScript FontName as that has no spaces and can separate family name from style name with a hyphen).

The renaming should affect:
- [ ] all INTERNAL names in the font
- [ ] the font file name
- [ ] the name of the repo
- [ ] the Glyphs file name
- [ ] anything else you come across during production/development

When it comes to renaming a file in the repo and keeping its history, this needs to be done through Github itself. Mirko or I can help you with this, ideally you don’t just delete the old file and add the new one. This would be important for the GlyphsApp (.glyphs) file in particular.

**Comment by bghryct** [comment]
The other "Danfo" font was renamed to my knowledge. I think we're safe to have Danfo as the name.
