### ISSUE TITLE
Some suggestions:

### ISSUE THREAD

**Issue by schriftgestalt** [Afrotype/danfo#2]
I had a look at the file. You can remove several things that are not needed.

- The Weight axis (as you already suspected). 
- The Axis Mapping parameter, as it is not mapping anything
- The first "Virtual Master" (Weight: 700, Shape: 0). This axis position is already defined by the regular master
- The "Variable Font Origin", as you only have one masters.

And the setup of the accents needs cleanup:
- You have stacked accents but most of the mark glyphs do not have a `top` anchor
- The diereiscomb is made form a regular scaled period and one that is rotated 180°. That will lead to misalignments.
- The dotbelowcomb either needs anchors, or you can rotate it by 180°, then it will convert the _top anchor from the dotaccentcomb. 

In general I would recommend to not add all available latin accented glyphs just because it is easy to do. Fix the design first and then add the accented glyphs in smaller batches and properly draw/setup all glyphs. Having a lot empty or wrong glyphs in a font is not helping.

**Comment by bghryct** [comment]
@schriftgestalt thanks for the feedback.

I'm going to implement your suggestions and see if the changes allow the builder to make a variable font out of the source. If not I think I will have to make an issue on the template repo.

**Comment by bghryct** [comment]
@schriftgestalt 

I've added your suggestions and the the GF builder still isn't recognizing the virtual master setup. 

I should mention the font builds correctly on Glyphs export

**Comment by schriftgestalt** [comment]
That is different problem. My suggestion were not targeting this.

**Comment by bghryct** [comment]
Yes understood. I'm working on a gf builder solution

**Comment by bghryct** [comment]
This is closed for now, while I find a GF friendly solution.
