### ISSUE TITLE
Latest Proof

### ISSUE THREAD

**Issue by Afrotype** [Afrotype/danfo#3]
[Danfo Proof, Letter.pdf](https://github.com/Afrotype/danfobase/files/13527966/Danfo.Proof.Letter.pdf)
(Friday, Dec 1)

**What's improved**
1. Fitting: We spaced out the letters to give consistent colour. 
2. Numbers: We've designed 0-9

**WIP**
1. Diacritics: Started work on these.
2. More language support.
3. Redrawing the S
4. Deciding what the cutouts look like

**What we need feedback on**
1. Numbers 0-9
2. Fitting and colour
3. Scale of diacritics

**Comment by Afrotype** [comment]
[Danfo Proof, Letter 2023-12-12 at 14.31.05.pdf](https://github.com/Afrotype/danfobase/files/13648674/Danfo.Proof.Letter.2023-12-12.at.14.31.05.pdf)

**What's improved**
Numbers: We modified the numbers in general and redesigned seven again.

**WIP**
Language Support: We have made a considerable pass here but are still refining.
Cutouts: We are in the final stages of deciding what the cutouts will look like.
Ksenya's Feedback: We are reading through and working in those updates.

**What we need feedback on**
Drawing in general
Number "7"
Any weird characters that jump out, especially in language support

**Comment by bghryct** [comment]
please update this list with a new proof showing the changes made in VF3 once everything has been migrated into the file.

**Comment by Afrotype** [comment]
[Danfo Proof, Letter 2024-01-30 at 14.37.22.pdf](https://github.com/Afrotype/danfo/files/14099011/Danfo.Proof.Letter.2024-01-30.at.14.37.22.pdf)

**What's been updated**
Diacritics: Fully designed
Punctuation: Fully designed
Symbols: Fully designed
Cutouts: Fully designed and merged
Burnishing: We have burnished all the sharp corners.

**WIP**
Language Support: We are currently proofing and refining.
Kerning: We have started kerning
Fractions: We are refining fractions.

**What we need feedback on**
Drawing: Any letters that seem problematic or could look better? Please let us know.
Language support from the Vietnamese specialists
Fractions: Proportions of numbers, etc
