### ISSUE TITLE
Burnishing Sharp/Acute Angles

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/danfo#4]
Per our call the other week, turning the sharp one-point angles into two-point ones for greater balance and harmony. 
<img width="485" alt="Screenshot 2023-12-10 at 8 43 09 PM" src="https://github.com/Afrotype/danfobase/assets/8194236/ad1598bc-a23d-4b9f-872e-da0b7c1d6f7c">

**Comment by bghryct** [comment]
is this meant to be for festac or also for danfo?

**Comment by samarskaya** [comment]
Meant for here… we discussed it for both. I think the space where it's most evident would be the interior spike in the O.

**Comment by bghryct** [comment]
gotcha. I went ahead and burnished a few other tight angles as well.

**Comment by bghryct** [comment]
This is being addressed.
