### ISSUE TITLE
Consider the Quasi-Tales (G U Q)

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/danfo#5]
I would look at the the glyphs with somewhat-tails, like the G, Q, and U, and work out a relationship as to how those are structured. Currently, the G and U have a similar shape, but it I’m not sure it’s as confident as the rest of the font, while the Q tail is doing a completely different movement. Consider the negative space as much as the positive. It might be okay and beneficial for the tail to get heft or to jut out to the right. 

If part of the brief is that this is something that gets cut out of vinyl, then you want the tails to be big enough that they wouldn’t accidentally get cut off.

**Comment by bghryct** [comment]
I think this has been resolved.
