### ISSUE TITLE
S

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/danfo#7]
Many of the letters feel very harmonious as to how they enter their platforms. The R is seamless. For the S, it feels forced and stuck—there’s not quite enough room for it to make the curve, and the bottom negative shape is very flat and somewhat incongruous. Options are to play with it within the given space, or to even make an exception where it can dip into the platform a bit to have room to make its curves. Another glyph to look at as an example that’s more successful is the B. While it still fits a lot of horizontals into that small space, the proportions are balanced. The top counter is smaller than the bottom one. On the S, the bottom counter is much narrower than the top one.

**Comment by bghryct** [comment]
This has been worked on.
