### ISSUE TITLE
M and the Widths

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/danfo#8]
Width is incredibly subjective, but I would extend the variation. The glyph where I’m seeing it the most is the M, which I would make much wider so that it doesn’t look so emaciated.

**Comment by bghryct** [comment]
This is being resolved alongside the VF integration of cut parts.

**Comment by bghryct** [comment]
Having tried a wider M, and also having tried incorporating more contrast in stroke width, and considering the symmetrical approach in cutting favored by the vinyl artists who make the letters upon which Danfo is based I've come to the conclusion that the 'narrow' symmetrical M is a reasonable solution. If we can come up with something better in line with your suggestion we will do that but in the meantime I'm closing this as completed.
