### ISSUE TITLE
N and the Diagonals

### ISSUE THREAD

**Issue by samarskaya** [Afrotype/danfo#9]
There’s an off-balance with the N. For the horizontal cross-bars, just adding them as something almost disjointed and placed atop seems to work. But for the diagonals, M, N, I want to see more integration and for them to align to how diagonals act for other glyphs such as the A, V, X. Incorporating the thick/thin as they are there should also help, rather than making the verticals thick and the interior diagonals cross-bar-like.

**Comment by bghryct** [comment]
I think this is being worked on and will be resolved imminently.

**Comment by bghryct** [comment]
completed.
